package net.top.framework.domain;
// Generated 2016-6-15 20:23:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * LogAnnocation generated by hbm2java
 */
public class OpLog implements java.io.Serializable {
    private Integer id;
    private String account;
    private String name;
    private String roleName;
    private String opName;
    private String opDescription;
    private Date opTime;
    private String opIp;

    public OpLog() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getOpName() {
        return opName;
    }

    public void setOpName(String opName) {
        this.opName = opName;
    }

    public String getOpDescription() {
        return opDescription;
    }

    public void setOpDescription(String opDescription) {
        this.opDescription = opDescription;
    }

    public Date getOpTime() {
        return opTime;
    }

    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    public String getOpIp() {
        return opIp;
    }

    public void setOpIp(String opIp) {
        this.opIp = opIp;
    }
}


