package net.top.framework.domain;
// Generated 2016-6-15 20:23:00 by Hibernate Tools 3.2.2.GA


/**
 * ResourceType generated by hbm2java
 */
public class ResourceType implements java.io.Serializable {


    private Integer id;
    private String name;
    private Integer order;
    private String icon;

    public ResourceType() {
    }

    public ResourceType(String name, Integer order, String icon) {
        this.name = name;
        this.order = order;
        this.icon = icon;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}


