package net.top.framework.domain;
// Generated 2016-6-15 20:23:00 by Hibernate Tools 3.2.2.GA


/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

    private Integer number;
    private String name;
    private String url;
    private Short isShow;
    private Integer order;
    private Integer resourceTypeId;
    private ResourceType resourceType;

    /**
     * 是否拥有该控制权限
     */
    private boolean isPrivilege;

    public Resource() {
    }


    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Short getIsShow() {
        return this.isShow;
    }

    public void setIsShow(Short isShow) {
        this.isShow = isShow;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Integer getResourceTypeId() {
        return resourceTypeId;
    }

    public void setResourceTypeId(Integer resourceTypeId) {
        this.resourceTypeId = resourceTypeId;
    }

    public ResourceType getResourceType() {
        return resourceType;
    }

    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    public boolean isPrivilege() {
        return isPrivilege;
    }

    public void setPrivilege(boolean privilege) {
        isPrivilege = privilege;
    }

    @Override
    public String toString() {
        return "Resource{" +
                "number='" + number + '\'' +
                ", name='" + name + '\'' +
                ", url='" + url + '\'' +
                ", isShow=" + isShow +
                ", order=" + order +
                ", resourceTypeId=" + resourceTypeId +
                ", resourceType=" + resourceType +
                '}';
    }
}


