package net.top.framework.domain;
// Generated 2016-6-15 20:23:00 by Hibernate Tools 3.2.2.GA


/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {


    private Integer number;
    private String name;
    private String remark;

    public Role() {
    }

    public Role(String name, String remark) {
        this.name = name;
        this.remark = remark;
    }

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        return "Role{" +
                "number=" + number +
                ", name='" + name + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}


