package net.top.framework.domain;
// Generated 2016-6-15 20:23:00 by Hibernate Tools 3.2.2.GA


/**
 * RolePopedom generated by hbm2java
 */
public class RolePopedom implements java.io.Serializable {


    private Integer id;
    private int roleNumber;
    private Integer resourceNumber;

    public RolePopedom() {
    }


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getRoleNumber() {
        return this.roleNumber;
    }

    public void setRoleNumber(int roleNumber) {
        this.roleNumber = roleNumber;
    }

    public Integer getResourceNumber() {
        return resourceNumber;
    }

    public void setResourceNumber(Integer resourceNumber) {
        this.resourceNumber = resourceNumber;
    }
}


